### ISSUE TITLE
Method not found: 'Void Telegram.Bot.TelegramBotClient..ctor(System.String, System.Net.Http.HttpClient)'

### ISSUE THREAD

**Issue by onatsko** [Bardin08/X.Serilog.Sinks.Telegram#37]
**Describe the bug**
After update to .NET 9 and Telegram.Bot to 22.1.0
get error

```
System.MissingMethodException: Method not found: 'Void Telegram.Bot.TelegramBotClient..ctor(System.String, System.Net.Http.HttpClient)'.
   at X.Serilog.Sinks.Telegram.TelegramSink..ctor(ChannelWriter`1 channelWriter, ILogsQueueAccessor logsQueueAccessor, TelegramSinkConfiguration sinkConfiguration, IMessageFormatter messageFormatter)
   at X.Serilog.Sinks.Telegram.Extensions.LoggerConfigurationTelegramExtensions.Telegram(LoggerSinkConfiguration loggerConfiguration, Action`1 configureAction, IMessageFormatter messageFormatter, LogEventLevel restrictedToMinimumLevel)
```

**Comment by Bardin08** [comment]
This will be resolved in a new version of the `X.Serilog.Sinks.Telegram` library as this logger merged with another similar project: https://github.com/dncuug/X.Serilog.Sinks.Telegram
